-- 코드를 입력하세요
/**
SELECT CAR_ID
     , AVG(DATEDIFF(END_DATE,START_DATE)) ASAVERAGE_DURATION
  FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
 #WHERE  
2	93
2	10
2	30
1	30
 ORDER BY CAR_ID DESC
 
 
  
  */
SELECT CAR_ID
     , ROUND(AVG(DATEDIFF(END_DATE, START_DATE) + 1), 1) AS AVERAGE_DURATION
  FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
 GROUP BY CAR_ID
HAVING AVERAGE_DURATION > 7
 ORDER BY AVERAGE_DURATION DESC
     , CAR_ID DESC
  /**
 SELECT CAR_ID
      , ROUND(AVG(DATEDIFF(END_DATE, START_DATE) + 1), 1) AS AVERAGE_DURATION
   FROM  CAR_RENTAL_COMPANY_RENTAL_HISTORY
   GROUP BY car_id
  HAVING AVG(DATEDIFF(END_DATE,START_DATE)) >= 7
   ORDER BY AVERAGE_DURATION DESC
       , CAR_ID DESC
 */
  