-- 코드를 입력하세요 
-- PRODUCT_CODE	SALES
SELECT PRODUCT_CODE, SUM(SALES_AMOUNT)*PRICE AS SALES
FROM PRODUCT A 
JOIN OFFLINE_SALE B 
ON A.product_id = B.product_id
GROUP BY product_code
ORDER BY  SUM(SALES_AMOUNT)*PRICE DESC, PRODUCT_CODE ASC